jobs:
  run:
    name: Action
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./test/main

name: Main

on:
  schedule:
    - cron: "15 */6 * * *"
